import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { writeFileSync, mkdirSync, rmSync, existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import {
  loadManifest,
  saveManifest,
  archiveCurrentArtifact,
  promoteArtifact,
  rollbackToFallback,
  pruneOldVersions,
  listVersions,
} from './artifact-versioning.js';
import type { ArtifactManifest } from './types.js';

let projectDir: string;

beforeEach(() => {
  projectDir = join(tmpdir(), `dream-ver-test-${Date.now()}-${Math.random().toString(36).slice(2)}`);
  mkdirSync(projectDir, { recursive: true });
});

afterEach(() => {
  rmSync(projectDir, { recursive: true, force: true });
});

describe('loadManifest / saveManifest', () => {
  it('returns empty manifest when no file exists', () => {
    const manifest = loadManifest(projectDir);
    expect(manifest.versions).toEqual([]);
    expect(manifest.currentVersion).toBe('');
  });

  it('round-trips a manifest', () => {
    const manifest: ArtifactManifest = {
      currentVersion: '/path/to/artifact.json',
      versions: [],
      lastManualVersion: '/path/to/manual.json',
    };
    saveManifest(projectDir, manifest);
    const loaded = loadManifest(projectDir);
    expect(loaded.currentVersion).toBe(manifest.currentVersion);
    expect(loaded.lastManualVersion).toBe(manifest.lastManualVersion);
  });
});

describe('archiveCurrentArtifact', () => {
  it('archives an existing artifact and updates manifest', () => {
    const artifactContent = JSON.stringify({ version: '0.1.0', stats: { toolCount: 5 } });
    writeFileSync(join(projectDir, 'tools.toolkit.json'), artifactContent);

    const version = archiveCurrentArtifact(projectDir, 'tools.toolkit.json', false);
    expect(version).not.toBeNull();
    expect(version!.toolCount).toBe(5);
    expect(version!.isAutoGenerated).toBe(false);
    expect(existsSync(version!.path)).toBe(true);

    const manifest = loadManifest(projectDir);
    expect(manifest.versions.length).toBe(1);
    expect(manifest.lastManualVersion).toBe(version!.path);
  });

  it('marks auto-generated versions correctly', () => {
    writeFileSync(join(projectDir, 'tools.toolkit.json'), '{"stats":{}}');

    const version = archiveCurrentArtifact(projectDir, 'tools.toolkit.json', true);
    expect(version!.isAutoGenerated).toBe(true);

    const manifest = loadManifest(projectDir);
    expect(manifest.lastManualVersion).toBeUndefined();
  });

  it('returns null when no artifact exists', () => {
    const version = archiveCurrentArtifact(projectDir, 'nonexistent.json', false);
    expect(version).toBeNull();
  });
});

describe('promoteArtifact', () => {
  it('copies new artifact to the output path', () => {
    const newPath = join(projectDir, 'new-artifact.json');
    writeFileSync(newPath, '{"new": true}');

    promoteArtifact(projectDir, newPath, 'tools.toolkit.json');

    const outputContent = readFileSync(join(projectDir, 'tools.toolkit.json'), 'utf-8');
    expect(JSON.parse(outputContent)).toEqual({ new: true });
  });
});

describe('rollbackToFallback', () => {
  it('restores the last manual version', () => {
    // Create and archive a manual version
    writeFileSync(join(projectDir, 'tools.toolkit.json'), '{"manual": true, "stats": {"toolCount": 3}}');
    archiveCurrentArtifact(projectDir, 'tools.toolkit.json', false);

    // Overwrite with auto version
    writeFileSync(join(projectDir, 'tools.toolkit.json'), '{"auto": true, "stats": {}}');
    archiveCurrentArtifact(projectDir, 'tools.toolkit.json', true);

    // Rollback
    const restored = rollbackToFallback(projectDir, 'tools.toolkit.json');
    expect(restored).not.toBeNull();
    expect(restored!.isAutoGenerated).toBe(false);

    const content = readFileSync(join(projectDir, 'tools.toolkit.json'), 'utf-8');
    expect(JSON.parse(content).manual).toBe(true);
  });

  it('returns null when no manual version exists', () => {
    writeFileSync(join(projectDir, 'tools.toolkit.json'), '{"stats":{}}');
    archiveCurrentArtifact(projectDir, 'tools.toolkit.json', true);

    const restored = rollbackToFallback(projectDir, 'tools.toolkit.json');
    expect(restored).toBeNull();
  });
});

describe('pruneOldVersions', () => {
  it('removes excess auto-generated versions first', () => {
    // Create several versions
    for (let i = 0; i < 7; i++) {
      writeFileSync(join(projectDir, 'tools.toolkit.json'), `{"v": ${i}, "stats": {}}`);
      archiveCurrentArtifact(projectDir, 'tools.toolkit.json', i !== 0); // first is manual
    }

    const manifest = loadManifest(projectDir);
    expect(manifest.versions.length).toBe(7);

    const deleted = pruneOldVersions(projectDir, 3);
    expect(deleted.length).toBeGreaterThan(0);

    const updatedManifest = loadManifest(projectDir);
    expect(updatedManifest.versions.length).toBeLessThanOrEqual(3);

    // Manual version should still exist
    const hasManual = updatedManifest.versions.some(v => !v.isAutoGenerated);
    expect(hasManual).toBe(true);
  });

  it('does nothing when within retention limit', () => {
    writeFileSync(join(projectDir, 'tools.toolkit.json'), '{"stats":{}}');
    archiveCurrentArtifact(projectDir, 'tools.toolkit.json', false);

    const deleted = pruneOldVersions(projectDir, 5);
    expect(deleted).toEqual([]);
  });
});

describe('listVersions', () => {
  it('returns all versions from manifest', () => {
    writeFileSync(join(projectDir, 'tools.toolkit.json'), '{"stats":{}}');
    archiveCurrentArtifact(projectDir, 'tools.toolkit.json', false);
    archiveCurrentArtifact(projectDir, 'tools.toolkit.json', true);

    const versions = listVersions(projectDir);
    expect(versions.length).toBe(2);
  });
});
