/**
 * ArtifactVersioning — manages versioned compiled artifacts with rollback.
 *
 * Artifacts are stored in `.smallchat/artifacts/` with timestamps.
 * A manifest.json tracks all versions and the current active version.
 * At least one non-auto-generated (manual) version is always retained
 * as a fallback.
 */

import {
  readFileSync,
  writeFileSync,
  copyFileSync,
  mkdirSync,
  unlinkSync,
  existsSync,
} from 'node:fs';
import { join, basename, dirname } from 'node:path';
import { createHash } from 'node:crypto';
import type { ArtifactManifest, ArtifactVersion } from './types.js';

// ---------------------------------------------------------------------------
// Paths
// ---------------------------------------------------------------------------

const ARTIFACTS_DIR = '.smallchat/artifacts';
const MANIFEST_FILE = 'manifest.json';

function artifactsDir(projectDir: string): string {
  return join(projectDir, ARTIFACTS_DIR);
}

function manifestPath(projectDir: string): string {
  return join(artifactsDir(projectDir), MANIFEST_FILE);
}

function ensureArtifactsDir(projectDir: string): void {
  mkdirSync(artifactsDir(projectDir), { recursive: true });
}

// ---------------------------------------------------------------------------
// Manifest management
// ---------------------------------------------------------------------------

/**
 * Load the artifact version manifest, or return a fresh empty manifest.
 */
export function loadManifest(projectDir: string): ArtifactManifest {
  const path = manifestPath(projectDir);

  if (!existsSync(path)) {
    return { currentVersion: '', versions: [] };
  }

  try {
    const content = readFileSync(path, 'utf-8');
    return JSON.parse(content) as ArtifactManifest;
  } catch {
    return { currentVersion: '', versions: [] };
  }
}

/**
 * Save the artifact version manifest to disk.
 */
export function saveManifest(projectDir: string, manifest: ArtifactManifest): void {
  ensureArtifactsDir(projectDir);
  writeFileSync(manifestPath(projectDir), JSON.stringify(manifest, null, 2) + '\n');
}

// ---------------------------------------------------------------------------
// Versioning operations
// ---------------------------------------------------------------------------

/**
 * Archive the current active artifact into the versioned store.
 * Returns the created ArtifactVersion, or null if no artifact exists.
 */
export function archiveCurrentArtifact(
  projectDir: string,
  outputPath: string,
  isAutoGenerated: boolean,
): ArtifactVersion | null {
  const sourcePath = join(projectDir, outputPath);

  if (!existsSync(sourcePath)) return null;

  ensureArtifactsDir(projectDir);

  const content = readFileSync(sourcePath, 'utf-8');
  const hash = createHash('sha256').update(content).digest('hex');
  const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
  const base = basename(outputPath, '.json');
  const suffix = isAutoGenerated ? '.auto' : '';
  const versionedName = `${base}.${timestamp}${suffix}.json`;
  const versionedPath = join(artifactsDir(projectDir), versionedName);

  copyFileSync(sourcePath, versionedPath);

  // Extract tool count from the artifact
  let toolCount = 0;
  try {
    const artifact = JSON.parse(content);
    toolCount = artifact.stats?.toolCount ?? 0;
  } catch {
    // Non-critical
  }

  const version: ArtifactVersion = {
    path: versionedPath,
    timestamp: new Date().toISOString(),
    isAutoGenerated,
    toolCount,
    hash,
  };

  // Update manifest
  const manifest = loadManifest(projectDir);
  manifest.versions.unshift(version); // newest first

  if (!isAutoGenerated) {
    manifest.lastManualVersion = versionedPath;
  }

  saveManifest(projectDir, manifest);

  return version;
}

/**
 * Promote a new artifact to be the active version.
 * Copies the artifact file to the output path and updates the manifest.
 */
export function promoteArtifact(
  projectDir: string,
  newArtifactPath: string,
  outputPath: string,
): void {
  const destPath = join(projectDir, outputPath);
  copyFileSync(newArtifactPath, destPath);

  const manifest = loadManifest(projectDir);
  manifest.currentVersion = destPath;
  saveManifest(projectDir, manifest);
}

/**
 * Rollback to the last non-auto-generated (manual) artifact version.
 * Returns the restored version, or null if no fallback exists.
 */
export function rollbackToFallback(
  projectDir: string,
  outputPath: string,
): ArtifactVersion | null {
  const manifest = loadManifest(projectDir);

  // Find the last manual version
  const manualVersion = manifest.versions.find(v => !v.isAutoGenerated);

  if (!manualVersion) {
    // Try lastManualVersion path
    if (manifest.lastManualVersion && existsSync(manifest.lastManualVersion)) {
      const content = readFileSync(manifest.lastManualVersion, 'utf-8');
      writeFileSync(join(projectDir, outputPath), content);
      manifest.currentVersion = join(projectDir, outputPath);
      saveManifest(projectDir, manifest);
      return {
        path: manifest.lastManualVersion,
        timestamp: new Date().toISOString(),
        isAutoGenerated: false,
        toolCount: 0,
        hash: createHash('sha256').update(content).digest('hex'),
      };
    }
    return null;
  }

  if (!existsSync(manualVersion.path)) return null;

  copyFileSync(manualVersion.path, join(projectDir, outputPath));
  manifest.currentVersion = join(projectDir, outputPath);
  saveManifest(projectDir, manifest);

  return manualVersion;
}

/**
 * Prune old artifact versions, respecting retention rules:
 * - Always keep at least 1 non-auto-generated version
 * - Keep up to maxRetained versions total
 * - Auto-generated versions are pruned first (oldest first)
 *
 * Returns paths that were deleted.
 */
export function pruneOldVersions(
  projectDir: string,
  maxRetained: number,
): string[] {
  const manifest = loadManifest(projectDir);
  const deleted: string[] = [];

  if (manifest.versions.length <= maxRetained) return deleted;

  // Separate manual and auto versions
  const manualVersions = manifest.versions.filter(v => !v.isAutoGenerated);
  const autoVersions = manifest.versions.filter(v => v.isAutoGenerated);

  // Calculate how many we need to prune
  const excess = manifest.versions.length - maxRetained;

  // Prune auto-generated versions first (oldest first = end of array since newest first)
  const autoPruneCount = Math.min(excess, autoVersions.length);
  const autoToPrune = autoVersions.slice(-autoPruneCount); // oldest auto versions

  for (const version of autoToPrune) {
    try {
      if (existsSync(version.path)) {
        unlinkSync(version.path);
      }
      deleted.push(version.path);
    } catch {
      // Skip if we can't delete
    }
  }

  // If we still need to prune more, remove old manual versions (but keep at least 1)
  const remaining = excess - autoPruneCount;
  if (remaining > 0 && manualVersions.length > 1) {
    const manualPruneCount = Math.min(remaining, manualVersions.length - 1);
    const manualToPrune = manualVersions.slice(-manualPruneCount); // oldest manual versions

    for (const version of manualToPrune) {
      // Never delete the lastManualVersion
      if (version.path === manifest.lastManualVersion) continue;

      try {
        if (existsSync(version.path)) {
          unlinkSync(version.path);
        }
        deleted.push(version.path);
      } catch {
        // Skip if we can't delete
      }
    }
  }

  // Update manifest to remove pruned versions
  const deletedSet = new Set(deleted);
  manifest.versions = manifest.versions.filter(v => !deletedSet.has(v.path));
  saveManifest(projectDir, manifest);

  return deleted;
}

/**
 * List all artifact versions from the manifest.
 */
export function listVersions(projectDir: string): ArtifactVersion[] {
  const manifest = loadManifest(projectDir);
  return manifest.versions;
}
