/**
 * Dream Module Types — shared interfaces for memory-driven tool re-compilation.
 *
 * The dream system reads Claude's memory files and session logs to discover
 * tool usage patterns, then re-compiles the tool manifest with informed priorities.
 */

// ---------------------------------------------------------------------------
// Log analysis types
// ---------------------------------------------------------------------------

/** A single observed tool usage extracted from Claude session logs. */
export interface ToolUsageRecord {
  toolName: string;
  providerId?: string;
  timestamp: string;
  success: boolean;
  /** True if the user immediately requested a different tool after this one. */
  userSwitchedAway: boolean;
  sessionId: string;
  durationMs?: number;
}

/** Aggregated statistics for a tool derived from log analysis. */
export interface ToolUsageStats {
  toolName: string;
  providerId?: string;
  totalCalls: number;
  successCount: number;
  failureCount: number;
  /** Times the user asked for a different tool immediately after this one. */
  switchAwayCount: number;
  /** Success rate as a fraction (0–1). */
  successRate: number;
  avgDurationMs?: number;
}

// ---------------------------------------------------------------------------
// Memory analysis types
// ---------------------------------------------------------------------------

/** Content read from a single memory file. */
export interface MemoryFileContent {
  path: string;
  content: string;
  modifiedAt: Date;
}

/** A tool mention extracted from a memory file with inferred sentiment. */
export interface MemoryToolMention {
  toolName: string;
  /** Surrounding text from the memory file that mentions this tool. */
  context: string;
  sentiment: 'positive' | 'negative' | 'neutral';
  /** Which memory file this mention was found in. */
  source: string;
}

// ---------------------------------------------------------------------------
// Priority hints (passed to the compiler)
// ---------------------------------------------------------------------------

/** Priority hints that influence compilation output. */
export interface ToolPriorityHints {
  /** Tools to boost — toolName → boost factor (>1.0 = boosted). */
  boosted: Map<string, number>;
  /** Tools to demote — toolName → demotion factor (<1.0 = demoted). */
  demoted: Map<string, number>;
  /** Tools to exclude entirely from the compiled artifact. */
  excluded: Set<string>;
  /** Human-readable reasoning for each priority decision. */
  reasoning: Map<string, string>;
}

// ---------------------------------------------------------------------------
// Dream analysis result
// ---------------------------------------------------------------------------

/** Complete result of a dream analysis pass. */
export interface DreamAnalysis {
  memoryMentions: MemoryToolMention[];
  usageStats: ToolUsageStats[];
  priorityHints: ToolPriorityHints;
  /** Human-readable summary report. */
  report: string;
  timestamp: string;
}

/** Result returned by compileLatest() / dream(). */
export interface DreamResult {
  analysis: DreamAnalysis;
  /** Path to the newly compiled artifact (or null if --dry-run). */
  artifactPath: string | null;
  /** Path to the archived previous artifact. */
  archivedPath: string | null;
  /** Whether the new artifact was automatically promoted. */
  autoPromoted: boolean;
}

// ---------------------------------------------------------------------------
// Configuration
// ---------------------------------------------------------------------------

/** Dream configuration — controls how compileLatest() behaves. */
export interface DreamConfig {
  /** Enable auto-dream (auto-replace artifact when dream runs). */
  autoDream: boolean;
  /** Additional paths to memory files (standard Claude locations always checked). */
  memoryPaths: string[];
  /** Path to Claude projects log directory (empty = auto-detect). */
  logDir: string;
  /** How many previous artifact versions to retain. */
  maxRetainedVersions: number;
  /** Output path for the compiled artifact. */
  outputPath: string;
  /** Source manifest path/directory (same as compile --source). */
  sourcePath?: string;
  /** Embedder type for compilation. */
  embedder: 'onnx' | 'local';
}

// ---------------------------------------------------------------------------
// Artifact versioning
// ---------------------------------------------------------------------------

/** Metadata for a single versioned artifact. */
export interface ArtifactVersion {
  /** Absolute path to the artifact file. */
  path: string;
  timestamp: string;
  /** True if this version was generated by auto-dream. */
  isAutoGenerated: boolean;
  /** Dream analysis that produced this version (if applicable). */
  dreamAnalysis?: DreamAnalysis;
  toolCount: number;
  /** SHA-256 hash of the artifact file content. */
  hash: string;
}

/** Manifest tracking all artifact versions for a project. */
export interface ArtifactManifest {
  /** Path to the currently active artifact. */
  currentVersion: string;
  /** All tracked artifact versions, newest first. */
  versions: ArtifactVersion[];
  /** Path to the last non-auto-generated version (always retained as fallback). */
  lastManualVersion?: string;
}
