import { Command } from 'commander';
import { resolve } from 'node:path';
import { compileLatest } from '../../dream/dream-compiler.js';
import { loadDreamConfig } from '../../dream/config.js';
import {
  rollbackToFallback,
  listVersions,
  promoteArtifact,
} from '../../dream/artifact-versioning.js';
import type { DreamConfig } from '../../dream/types.js';

export const dreamCommand = new Command('dream')
  .description('Re-compile tools using Claude memory and session log insights')
  .option('-s, --source [path]', 'Source manifests (same as compile --source)')
  .option('-o, --output <path>', 'Output artifact path')
  .option('-e, --embedder <type>', 'Embedder: onnx or local')
  .option('--auto', 'Enable auto-dream (replace artifact without confirmation)')
  .option('--memory <paths...>', 'Additional memory file paths')
  .option('--log-dir <path>', 'Claude log directory')
  .option('--dry-run', 'Analyze and report without compiling')
  .option('--config <path>', 'Path to smallchat.dream.json')
  .option('--rollback', 'Rollback to last non-auto-generated artifact')
  .option('--list-versions', 'List all artifact versions')
  .option('--confirm', 'Confirm replacement of active artifact (non-auto mode)')
  .action(async (options) => {
    const projectDir = process.cwd();

    // --- Rollback mode ---
    if (options.rollback) {
      const config = loadDreamConfig(undefined, options.config);
      const restored = rollbackToFallback(projectDir, config.outputPath);
      if (restored) {
        console.log(`Rolled back to: ${restored.path}`);
        console.log(`  Timestamp: ${restored.timestamp}`);
        console.log(`  Tools: ${restored.toolCount}`);
      } else {
        console.error('No fallback version available. No manual (non-auto-generated) artifact found.');
        process.exit(1);
      }
      return;
    }

    // --- List versions mode ---
    if (options.listVersions) {
      const versions = listVersions(projectDir);
      if (versions.length === 0) {
        console.log('No artifact versions found.');
        return;
      }

      console.log('Artifact versions:\n');
      for (const v of versions) {
        const autoLabel = v.isAutoGenerated ? ' [auto]' : ' [manual]';
        console.log(`  ${v.timestamp}${autoLabel}`);
        console.log(`    Path: ${v.path}`);
        console.log(`    Tools: ${v.toolCount}`);
        console.log(`    Hash: ${v.hash.slice(0, 12)}...`);
        console.log('');
      }
      return;
    }

    // --- Dream mode ---
    const configOverrides: Partial<DreamConfig> = {};
    if (options.source) configOverrides.sourcePath = resolve(options.source);
    if (options.output) configOverrides.outputPath = options.output;
    if (options.embedder) configOverrides.embedder = options.embedder;
    if (options.auto) configOverrides.autoDream = true;
    if (options.memory) configOverrides.memoryPaths = options.memory.map((p: string) => resolve(p));
    if (options.logDir) configOverrides.logDir = resolve(options.logDir);

    const result = await compileLatest({
      configOverrides,
      configPath: options.config,
      dryRun: options.dryRun,
      projectDir,
    });

    // If not auto-promoted and not dry-run, ask about confirmation
    if (!result.autoPromoted && result.artifactPath && options.confirm) {
      const config = loadDreamConfig(configOverrides, options.config);
      promoteArtifact(projectDir, result.artifactPath, config.outputPath);
      console.log(`\nPromoted new artifact to: ${config.outputPath}`);
    } else if (!result.autoPromoted && result.artifactPath && !options.dryRun) {
      console.log('\nTo apply the new artifact, run:');
      console.log(`  smallchat dream --confirm`);
      console.log('Or to enable auto-replacement:');
      console.log(`  smallchat dream --auto`);
    }
  });
